- helloWorld.rb
> Hello world in Ruby!

- README.md
- helloWorld.clj
> Adding helloworld in clojure

- helloWorld.php
> Hello World in php #3

- README.md
- helloWorld-roringbbk.rb
This PR contains the file that prints "Hello world" text using Ruby.
> Add file to print text in ruby

- helloWorld.rb
added hello world in html. i am not sure if i did this right... as i am a beginner lol
> Updated Hello World

- helloWorld.rb
- helloworld.f
Hello World in Fortran (helloworld.f);
Removed '--ruby' from 'helloWorld.rb' so that it runs from cli.
> Hello World in Fortran

- helloWorld.kt
> Hello Kotlin

- HelloWorld-mikegv.rb
Added HelloWorld-mikegv.rb in branch ruby-mikegv.
> HelloWorld-mikegv.rb

- helloworld.rs
> Add hello world Rust

- hello_world.scala
> Add Scala version of Hello World program

- README.md
- halloWelt.php
Thanks for creating this project!
> Roger's commit

- hellowrld-dj.sh
> hacktoberfest hello

- README.md
With the issues merging my pull requests, the one where I added myself to the README was closed [#8], while my 2nd (Java) request [#9] was merged.
> Added myself to Contributors

- README.md
- hello_world.rb
* Add hello_world.rb file that outputs a Hello World message
* Update README with username
> Add hello world for Ruby and update Readme

- helloworld-obsidianspork.js
- helloworld.c
> add semicolon

- variableworlds.sh
> Check this son 

- README.md
- helloworld-kovloq.rb
> Hacktoberfest New pull request

- README.md
- helloworld-kungfuguapo.php
**PHP is like affogato before brooklyn sold out to fingerstache mumblecore.** - @kungfuguapo
> PHP is the bossa nova of the code world

- helloworld.wrl
Haven't 'played' with vrml since 1997 :)
> Hello World! in VRML

- hello.ex
> Hello, elixir!

- hellopython3.py
- helloworld.vala
> Add vala and python3

- README.md
- hello_world-guptarohit.py
Added "Hello world" file for **Python**.
And also updated _README.md_ file.
This solves #3. 😄
> Added "Hello world" for Python and updated Readme file.

- helloworld.x
woah woah there... are we actually doing something constructive?
> My first commit for helloworld

- hello_world.cfm
- hello_world.ml
- hello_world.zsh
> Add Coldfusion

- helloworld.x
> i need this line..

- helloWorld.4gl
> Adding 4gl hello world

- Hello world - jb-1980.py
> Create Hello world - jb-1980.py

- README.md
- README.md~
- helloworldpy.py
please merge me with label hacktoberfest!!!! Thanks you
> python file

- README.md
- hello-world.clips
CLIPS is a public domain software tool for building expert systems. CLIPS stands for "C Language Integrated Production System."
> Prints Hello World in clips Language

- helloworldpy.py
> What is hacktoberfest?!

- HelloWorld.birl
- README.md
Wrote hello world in birl (brazilian inner joke language)
You can check more at https://birl-language.github.io/
Thanks :smile:
> Hello world in birl more info: https://birl-language.github.io/

- README.md
- helloworld-vitaliaventel.java
> Hello world java

- HelloWorld.s
- README.md
- Hello World in Assembly Language.
- Updated README.md
- This is in regard to #3.
> Hello World In Assembly Language

- README.md
- hello-world.css
> Hello World in CSS

- HelloWorld2.7.py
> hello world in python 2.7

- Hello_World.html
https://github.com/obsidianspork/hacktoberfest-dcoy/issues/3
> add hello hacktoberfest

- hola_mundo_en_php.html
> hello world php

- hello_hacktoberfest.py
> add hello in python

- differentHelloWorld.java
- helloWorld Java/MorningWorld.java
Adding a different "Hello world"
> Innusual hello world

- HolaMundo
> Create Hola Mundo

- hello-world-Nishanth4.cpp
> Added hello world in C++

- HelloWorld-mudit9.c
> added helloworld-mudit9.c

- README.md
- hello-world-iife.js
Created hello world in Javascript using IIFE.
> Created hello world in Javascript using IIFE.

- Hello-world-hoxank.c
hopefully everything is correct thanks
> added hello world in c

- README.md
- helloworld-cl1ent.go
- added .go file
- added myself to contributors list
> added go helloworld file

- H3ll0 w0rlD.py
> Create a new hello world

- gitc.sh
Simple bash script for adding and commiting in git 
Issue : #3
> Bash script to add and commit files in git

- README.md
- hello_world.cr
> Add Hello World in Crystal

- README.md
- hello-world-carmarshall.php
Add username to README.md
Add hello-world-carmarshall.php to Repo
> Add Personal Contribution To README And Repo

- README.md
- hello_world.bef
Found it randomly on wikipedia esoteric [languages](https://en.wikipedia.org/wiki/Befunge)
> Added Befunge language hello world

- helloworld-kartikburmee25.py
> added new helloworld program written in python programming language.

- hello_worlddd.py
> hello world

- helloWorldInVerilog.txt
Code for printing Hello World in Verilog Language
This pull request resolves issue #3
> Hello World in Verilog

- helloworld1.py
created a "hello world" program in python
> Helloworld1
